### ISSUE TITLE
Any plan for floor?

### ISSUE THREAD

**Issue by khushaljethava** [akshay-rf/Kanso#1]
Hello,
amazing work, are you planning to implement the same with the floor for texture?

**Comment by akshay-rf** [comment]
Hi there, yes i intend add floor and ceiling customization after creating a stable release for the app. This project was done as part of a hackathon in 12 hours. I'm glad you liked it.

**Comment by vsvipul11** [comment]
Hi your project is really amazing, Have you made anything regarding the floor?
